import { Team, Mode } from './types'

export const TEAMS: Team[] = [
  { g:'A', flag:'🇲🇽', name:'Mexico', abbr:'MEX', conf:'CONCACAF',
    auth:{ drink:'Mezcal', desc:'Smoky agave spirit — sip it like you mean it', wiki:'https://en.wikipedia.org/wiki/Mezcal' },
    usa:{ drink:'Tequila Shot', desc:'Patron, Casamigos, or whatever well tequila is back there', wiki:'https://en.wikipedia.org/wiki/Tequila' },
    beer:{ drink:"Corona", desc:"Pale lager — lime in the neck, toes in the sand", wiki:"https://en.wikipedia.org/wiki/Corona_(beer)" } },
  { g:'A', flag:'🇿🇦', name:'South Africa', abbr:'RSA', conf:'CAF',
    auth:{ drink:'Amarula', desc:'Cream liqueur made from marula fruit', wiki:'https://en.wikipedia.org/wiki/Amarula' },
    usa:{ drink:'Baileys Shot', desc:"Closest cream liqueur you'll find — close enough", wiki:'https://en.wikipedia.org/wiki/Baileys_Irish_Cream' },
    beer:{ drink:"Castle Lager", desc:"South Africa's golden braai-side lager", wiki:"https://en.wikipedia.org/wiki/Castle_Lager" } },
  { g:'A', flag:'🇰🇷', name:'South Korea', abbr:'KOR', conf:'AFC',
    auth:{ drink:'Soju', desc:"Korea's beloved rice spirit, deceptively smooth", wiki:'https://en.wikipedia.org/wiki/Soju' },
    usa:{ drink:'Soju', desc:'Actually everywhere now — H Mart, Total Wine, most liquor stores', wiki:'https://en.wikipedia.org/wiki/Soju' },
    beer:{ drink:"Cass", desc:"Crisp fizzy lager — Korea's BBQ-table beer", wiki:"https://en.wikipedia.org/wiki/Oriental_Brewery" } },
  { g:'A', flag:'🇨🇿', name:'Czechia', abbr:'CZE', conf:'UEFA',
    auth:{ drink:'Becherovka', desc:'Herbal bitters from Karlovy Vary', wiki:'https://en.wikipedia.org/wiki/Becherovka' },
    usa:{ drink:'Jägermeister', desc:'Both are herbal digestifs — Jager is just easier to find', wiki:'https://en.wikipedia.org/wiki/J%C3%A4germeister' },
    beer:{ drink:"Pilsner Urquell", desc:"The original pilsner — Plzeň, 1842", wiki:"https://en.wikipedia.org/wiki/Pilsner_Urquell" } },
  { g:'B', flag:'🇨🇭', name:'Switzerland', abbr:'SUI', conf:'UEFA',
    auth:{ drink:'Kirsch', desc:'Clear cherry brandy from the Alps', wiki:'https://en.wikipedia.org/wiki/Kirschwasser' },
    usa:{ drink:'Cherry Vodka Shot', desc:'Smirnoff Cherry or Absolut — close enough vibes', wiki:'https://en.wikipedia.org/wiki/Vodka' },
    beer:{ drink:"Feldschlösschen", desc:"Switzerland's best-seller, brewed in a castle", wiki:"https://en.wikipedia.org/wiki/Feldschl%C3%B6sschen" } },
  { g:'B', flag:'🇨🇦', name:'Canada', abbr:'CAN', conf:'CONCACAF',
    auth:{ drink:'Canadian Whisky', desc:'Smooth rye whisky — Crown Royal or bust', wiki:'https://en.wikipedia.org/wiki/Canadian_whisky' },
    usa:{ drink:'Crown Royal', desc:'Crown Royal is literally everywhere — no sub needed', wiki:'https://en.wikipedia.org/wiki/Crown_Royal' },
    beer:{ drink:"Molson Canadian", desc:"Easy-drinking lager — as Canadian as it gets, eh", wiki:"https://en.wikipedia.org/wiki/Molson_Canadian" } },
  { g:'B', flag:'🇶🇦', name:'Qatar', abbr:'QAT', conf:'AFC',
    auth:{ drink:'Arak', desc:'Anise-flavored spirit, goes cloudy with water', wiki:'https://en.wikipedia.org/wiki/Arak_(drink)' },
    usa:{ drink:'Sambuca', desc:'Italian anise liqueur — same vibe, way more available', wiki:'https://en.wikipedia.org/wiki/Sambuca' },
    beer:{ drink:"Barbican", desc:"Non-alcoholic malt — the Gulf's go-to in a dry nation", wiki:"https://en.wikipedia.org/wiki/Barbican_(drink)" } },
  { g:'B', flag:'🇧🇦', name:'Bosnia & Herz.', abbr:'BIH', conf:'UEFA',
    auth:{ drink:'Rakija', desc:'Balkan plum brandy — rough, strong, traditional', wiki:'https://en.wikipedia.org/wiki/Rakija' },
    usa:{ drink:'Slivovitz or Brandy', desc:'Eastern European delis carry it — otherwise any dark brandy', wiki:'https://en.wikipedia.org/wiki/Slivovitz' },
    beer:{ drink:"Sarajevsko", desc:"Sarajevo's pride, pouring since 1864", wiki:"https://en.wikipedia.org/wiki/Sarajevska_pivara" } },
  { g:'C', flag:'🇧🇷', name:'Brazil', abbr:'BRA', conf:'CONMEBOL',
    auth:{ drink:'Cachaça', desc:'Sugar cane spirit — base of the caipirinha', wiki:'https://en.wikipedia.org/wiki/Cacha%C3%A7a' },
    usa:{ drink:'Cachaça or White Rum', desc:'Leblon at most Total Wine stores — or use white rum', wiki:'https://en.wikipedia.org/wiki/Rum' },
    beer:{ drink:"Brahma", desc:"Ice-cold Brazilian lager — chope on the beach", wiki:"https://en.wikipedia.org/wiki/Brahma_(beer)" } },
  { g:'C', flag:'🇲🇦', name:'Morocco', abbr:'MAR', conf:'CAF',
    auth:{ drink:'Mahia', desc:'North African fig brandy, a rare pour', wiki:'https://en.wikipedia.org/wiki/Mahia_(drink)' },
    usa:{ drink:'Brandy Shot', desc:'Fig brandy is impossible to find — sub any fruit brandy', wiki:'https://en.wikipedia.org/wiki/Brandy' },
    beer:{ drink:"Casablanca", desc:"Morocco's crisp pale lager", wiki:"https://en.wikipedia.org/wiki/Beer_in_Morocco" } },
  { g:'C', flag:'🏴󠁧󠁢󠁳󠁣󠁴󠁿', name:'Scotland', abbr:'SCO', conf:'UEFA',
    auth:{ drink:'Scotch Whisky', desc:'Single malt, neat — no ice, no apologies', wiki:'https://en.wikipedia.org/wiki/Scotch_whisky' },
    usa:{ drink:'Scotch Shot', desc:"Dewar's, Johnnie Walker Black, or Monkey Shoulder — at every bar", wiki:'https://en.wikipedia.org/wiki/Scotch_whisky' },
    beer:{ drink:"Tennent's", desc:"Glasgow's lager — a proper Scottish session", wiki:"https://en.wikipedia.org/wiki/Tennent_Caledonian" } },
  { g:'C', flag:'🇨🇩', name:'Congo DR', abbr:'COD', conf:'CAF',
    auth:{ drink:'Lotoko', desc:'Congolese corn spirit — powerful moonshine', wiki:'https://en.wikipedia.org/wiki/Lotoko' },
    usa:{ drink:'Ole Smoky Moonshine', desc:'American moonshine is the closest readily available cousin', wiki:'https://en.wikipedia.org/wiki/Moonshine' },
    beer:{ drink:"Primus", desc:"Kinshasa's classic lager since 1923", wiki:"https://en.wikipedia.org/wiki/Bralima" } },
  { g:'D', flag:'🇺🇸', name:'USA', abbr:'USA', conf:'CONCACAF',
    auth:{ drink:'Bourbon', desc:'Kentucky straight — America in a glass', wiki:'https://en.wikipedia.org/wiki/Bourbon_whiskey' },
    usa:{ drink:'Bourbon', desc:"You're already home. Maker's Mark, Bulleit, or Jim Beam", wiki:'https://en.wikipedia.org/wiki/Bourbon_whiskey' },
    beer:{ drink:"Budweiser", desc:"The self-styled King of Beers, ice cold", wiki:"https://en.wikipedia.org/wiki/Budweiser" } },
  { g:'D', flag:'🇦🇺', name:'Australia', abbr:'AUS', conf:'AFC',
    auth:{ drink:'Tim Tam Slam', desc:'Bite both ends, sip hot choc through the cookie', wiki:'https://en.wikipedia.org/wiki/Tim_Tam#Tim_Tam_Slam' },
    usa:{ drink:'Fireball Shot', desc:'Warm, sweet, universally stocked — Aussie bars love Fireball too', wiki:'https://en.wikipedia.org/wiki/Fireball_Cinnamon_Whisky' },
    beer:{ drink:"Foster's", desc:"Australian for beer — the tinnie icon", wiki:"https://en.wikipedia.org/wiki/Foster%27s_Lager" } },
  { g:'D', flag:'🇹🇷', name:'Turkiye', abbr:'TUR', conf:'UEFA',
    auth:{ drink:'Rakı', desc:"Lion's milk — anise spirit, ice water chaser", wiki:'https://en.wikipedia.org/wiki/Rak%C4%B1' },
    usa:{ drink:'Sambuca', desc:'Italian anise spirit — same character, at every bar', wiki:'https://en.wikipedia.org/wiki/Sambuca' },
    beer:{ drink:"Efes", desc:"Efes Pilsen — Turkey's iconic lager", wiki:"https://en.wikipedia.org/wiki/Efes_Beverage_Group" } },
  { g:'D', flag:'🇬🇭', name:'Ghana', abbr:'GHA', conf:'CAF',
    auth:{ drink:'Akpeteshie', desc:'Powerful palm wine distillate from West Africa', wiki:'https://en.wikipedia.org/wiki/Akpeteshie' },
    usa:{ drink:'Overproof Rum Shot', desc:"Gosling's Black Seal or Bacardi 151 — same raw-spirit energy", wiki:'https://en.wikipedia.org/wiki/Overproof_rum' },
    beer:{ drink:"Star", desc:"Ghana's original lager since 1931", wiki:"https://en.wikipedia.org/wiki/Guinness_Ghana_Breweries" } },
  { g:'E', flag:'🇩🇪', name:'Germany', abbr:'GER', conf:'UEFA',
    auth:{ drink:'Jägermeister', desc:'56-herb digestif — prost!', wiki:'https://en.wikipedia.org/wiki/J%C3%A4germeister' },
    usa:{ drink:'Jägermeister', desc:'No sub needed — Jager is in every single American bar', wiki:'https://en.wikipedia.org/wiki/J%C3%A4germeister' },
    beer:{ drink:"Beck's", desc:"German pilsner from Bremen — prost!", wiki:"https://en.wikipedia.org/wiki/Beck%27s_Brewery" } },
  { g:'E', flag:'🇨🇮', name:'Ivory Coast', abbr:'CIV', conf:'CAF',
    auth:{ drink:'Koutoukou', desc:'Palm wine hooch — fiery West African spirit', wiki:'https://en.wikipedia.org/wiki/Koutoukou' },
    usa:{ drink:'Overproof Rum', desc:'Plantation OFTD or Smith & Cross — funky, fierce, similar energy', wiki:'https://en.wikipedia.org/wiki/Overproof_rum' },
    beer:{ drink:"Flag", desc:"West Africa's everyday golden lager", wiki:"https://en.wikipedia.org/wiki/Beer_in_Africa" } },
  { g:'E', flag:'🇪🇨', name:'Ecuador', abbr:'ECU', conf:'CONMEBOL',
    auth:{ drink:'Canelazo', desc:'Warm cinnamon & sugarcane spirit punch', wiki:'https://en.wikipedia.org/wiki/Canelazo' },
    usa:{ drink:'Fireball Shot', desc:'Cinnamon + sugarcane vibes — Fireball is basically Canelazo in a shot', wiki:'https://en.wikipedia.org/wiki/Fireball_Cinnamon_Whisky' },
    beer:{ drink:"Pilsener", desc:"Ecuador's beloved pale lager", wiki:"https://en.wikipedia.org/wiki/Pilsner" } },
  { g:'E', flag:'🇨🇼', name:'Curacao', abbr:'CUW', conf:'CONCACAF',
    auth:{ drink:'Blue Curaçao', desc:"Orange liqueur, impossibly blue — it's their thing", wiki:'https://en.wikipedia.org/wiki/Cura%C3%A7ao_(liqueur)' },
    usa:{ drink:'Blue Curaçao Shot', desc:'DeKuyper Blue Curaçao is literally everywhere — this one is easy', wiki:'https://en.wikipedia.org/wiki/Cura%C3%A7ao_(liqueur)' },
    beer:{ drink:"Amstel Bright", desc:"Light tropical lager — the Caribbean Amstel", wiki:"https://en.wikipedia.org/wiki/Amstel_Brewery" } },
  { g:'F', flag:'🇳🇱', name:'Netherlands', abbr:'NED', conf:'UEFA',
    auth:{ drink:'Jenever', desc:'Dutch gin ancestor — the original G&T', wiki:'https://en.wikipedia.org/wiki/Jenever' },
    usa:{ drink:'Gin Shot', desc:'Tanqueray or Bombay Sapphire — Dutch and London gin share DNA', wiki:'https://en.wikipedia.org/wiki/Gin' },
    beer:{ drink:"Heineken", desc:"The green bottle that conquered the world", wiki:"https://en.wikipedia.org/wiki/Heineken" } },
  { g:'F', flag:'🇯🇵', name:'Japan', abbr:'JPN', conf:'AFC',
    auth:{ drink:'Shochu', desc:'Distilled spirit, lighter than sake, more complex', wiki:'https://en.wikipedia.org/wiki/Sh%C5%8Dch%C5%AB' },
    usa:{ drink:'Sake Shot', desc:'More available than shochu — Gekkeikan at most grocery stores', wiki:'https://en.wikipedia.org/wiki/Sake' },
    beer:{ drink:"Asahi Super Dry", desc:"Karakuchi — crisp, dry, razor finish", wiki:"https://en.wikipedia.org/wiki/Asahi_Breweries" } },
  { g:'F', flag:'🇸🇪', name:'Sweden', abbr:'SWE', conf:'UEFA',
    auth:{ drink:'Aquavit', desc:'Caraway-spiced Scandinavian spirit, served ice cold', wiki:'https://en.wikipedia.org/wiki/Aquavit' },
    usa:{ drink:'Aquavit', desc:'Linie Aquavit is at most Total Wine — no sub needed', wiki:'https://en.wikipedia.org/wiki/Aquavit' },
    beer:{ drink:"Pripps Blå", desc:"Sweden's blue-label everyday lager", wiki:"https://en.wikipedia.org/wiki/Pripps" } },
  { g:'F', flag:'🇹🇳', name:'Tunisia', abbr:'TUN', conf:'CAF',
    auth:{ drink:'Boukha', desc:'Fig eau-de-vie from Tunisia — subtle and fragrant', wiki:'https://en.wikipedia.org/wiki/Boukha' },
    usa:{ drink:'Pisco Shot', desc:'Another fruit brandy — aromatic, found at decent liquor stores', wiki:'https://en.wikipedia.org/wiki/Pisco' },
    beer:{ drink:"Celtia", desc:"Tunisia's sunny Mediterranean lager", wiki:"https://en.wikipedia.org/wiki/Celtia" } },
  { g:'G', flag:'🇧🇪', name:'Belgium', abbr:'BEL', conf:'UEFA',
    auth:{ drink:'Jenever', desc:'Belgian-style genever, the OG gin', wiki:'https://en.wikipedia.org/wiki/Jenever' },
    usa:{ drink:'Gin Shot', desc:"Hendrick's or Tanqueray — both carry that botanical jenever DNA", wiki:'https://en.wikipedia.org/wiki/Gin' },
    beer:{ drink:"Stella Artois", desc:"Belgian lager since 1926 — the chalice pour", wiki:"https://en.wikipedia.org/wiki/Stella_Artois" } },
  { g:'G', flag:'🇮🇷', name:'Iran', abbr:'IRN', conf:'AFC',
    auth:{ drink:'Aragh Sagi', desc:'Traditional Iranian raisin moonshine', wiki:'https://en.wikipedia.org/wiki/Aragh_sagi' },
    usa:{ drink:'Grappa Shot', desc:'Italian grape pomace brandy — closest readily available sub', wiki:'https://en.wikipedia.org/wiki/Grappa' },
    beer:{ drink:"Delster", desc:"Non-alcoholic malt — Iran's bottled standard", wiki:"https://en.wikipedia.org/wiki/Beer_in_Iran" } },
  { g:'G', flag:'🇪🇬', name:'Egypt', abbr:'EGY', conf:'CAF',
    auth:{ drink:'Zibib', desc:'Egyptian anise spirit, cousin of Greek ouzo', wiki:'https://en.wikipedia.org/wiki/Zibib' },
    usa:{ drink:'Ouzo Shot', desc:"Greek ouzo is Zibib's cousin — found at Greek restaurants and Total Wine", wiki:'https://en.wikipedia.org/wiki/Ouzo' },
    beer:{ drink:"Stella", desc:"Egypt's classic lager since 1897 (not the Belgian one)", wiki:"https://en.wikipedia.org/wiki/Stella_(beer)" } },
  { g:'G', flag:'🇺🇿', name:'Uzbekistan', abbr:'UZB', conf:'AFC',
    auth:{ drink:'Starka Vodka', desc:'Aged rye vodka from Central Asia', wiki:'https://en.wikipedia.org/wiki/Starka' },
    usa:{ drink:'Rye Whiskey Shot', desc:'Bulleit Rye or Rittenhouse — aged grain spirit, same ballpark', wiki:'https://en.wikipedia.org/wiki/Rye_whiskey' },
    beer:{ drink:"Sarbast", desc:"Uzbekistan's leading lager", wiki:"https://en.wikipedia.org/wiki/Sarbast" } },
  { g:'H', flag:'🇪🇸', name:'Spain', abbr:'ESP', conf:'UEFA',
    auth:{ drink:'Orujo', desc:'Spanish pomace brandy — bold and rustic', wiki:'https://en.wikipedia.org/wiki/Orujo' },
    usa:{ drink:'Grappa Shot', desc:'Italian pomace brandy — same grape-skin base, same rustic kick', wiki:'https://en.wikipedia.org/wiki/Grappa' },
    beer:{ drink:"Estrella Damm", desc:"Barcelona's Mediterranean lager since 1876", wiki:"https://en.wikipedia.org/wiki/Estrella_Damm" } },
  { g:'H', flag:'🇺🇾', name:'Uruguay', abbr:'URU', conf:'CONMEBOL',
    auth:{ drink:'Grappamiel', desc:'Honey grappa — sweet, warming, very Uruguayan', wiki:'https://en.wikipedia.org/wiki/Grappamiel' },
    usa:{ drink:'Drambuie Shot', desc:'Honey + spirit liqueur — sweet and warming just like Grappamiel', wiki:'https://en.wikipedia.org/wiki/Drambuie' },
    beer:{ drink:"Norteña", desc:"Uruguay's smooth, balanced lager", wiki:"https://en.wikipedia.org/wiki/Cerveza_Norte%C3%B1a" } },
  { g:'H', flag:'🇨🇻', name:'Cape Verde', abbr:'CPV', conf:'CAF',
    auth:{ drink:'Grogue', desc:'Unaged sugarcane rum, rough and authentic', wiki:'https://en.wikipedia.org/wiki/Grogue_(liquor)' },
    usa:{ drink:'White Rum Shot', desc:'Bacardi Silver or Plantation 3 Star — unaged sugarcane, same idea', wiki:'https://en.wikipedia.org/wiki/Rum' },
    beer:{ drink:"Strela", desc:"Cape Verde's island lager, named for a star", wiki:"https://en.wikipedia.org/wiki/Strela_(beer)" } },
  { g:'H', flag:'🇸🇦', name:'Saudi Arabia', abbr:'KSA', conf:'AFC',
    auth:{ drink:'Arak', desc:'Traditional Middle Eastern anise spirit', wiki:'https://en.wikipedia.org/wiki/Arak_(drink)' },
    usa:{ drink:'Sambuca', desc:"Italian anise liqueur — Sambuca is Arak's party cousin", wiki:'https://en.wikipedia.org/wiki/Sambuca' },
    beer:{ drink:"Barbican", desc:"Non-alcoholic malt — the Saudi standard", wiki:"https://en.wikipedia.org/wiki/Barbican_(drink)" } },
  { g:'I', flag:'🇫🇷', name:'France', abbr:'FRA', conf:'UEFA',
    auth:{ drink:'Cognac', desc:'Aged grape brandy — sophistication in a snifter', wiki:'https://en.wikipedia.org/wiki/Cognac' },
    usa:{ drink:'Hennessy VS Shot', desc:'Henny is in every bar in America — French cognac, no sub needed', wiki:'https://en.wikipedia.org/wiki/Hennessy' },
    beer:{ drink:"Kronenbourg 1664", desc:"Alsace lager — France in a blue can", wiki:"https://en.wikipedia.org/wiki/Kronenbourg_Brewery" } },
  { g:'I', flag:'🇸🇳', name:'Senegal', abbr:'SEN', conf:'CAF',
    auth:{ drink:'Bissap', desc:'Hibiscus liqueur — floral and bittersweet', wiki:'https://en.wikipedia.org/wiki/Bissap' },
    usa:{ drink:'St-Germain Shot', desc:'Elderflower liqueur — floral, slightly sweet, same energy', wiki:'https://en.wikipedia.org/wiki/St-Germain_(liqueur)' },
    beer:{ drink:"Gazelle", desc:"Senegal's light, refreshing lager", wiki:"https://en.wikipedia.org/wiki/Beer_in_Africa" } },
  { g:'I', flag:'🇳🇴', name:'Norway', abbr:'NOR', conf:'UEFA',
    auth:{ drink:'Linie Aquavit', desc:'Aged at sea crossing the equator twice — unique', wiki:'https://en.wikipedia.org/wiki/Linie_Aquavit' },
    usa:{ drink:'Aquavit', desc:'Linie is at Total Wine — or use Absolut Dill as a wild card sub', wiki:'https://en.wikipedia.org/wiki/Aquavit' },
    beer:{ drink:"Ringnes", desc:"Norway's classic lager since 1876", wiki:"https://en.wikipedia.org/wiki/Ringnes" } },
  { g:'I', flag:'🇳🇿', name:'New Zealand', abbr:'NZL', conf:'OFC',
    auth:{ drink:'Manuka Whisky', desc:'Honey-infused whisky with New Zealand botanicals', wiki:'https://en.wikipedia.org/wiki/Whisky_in_New_Zealand' },
    usa:{ drink:'Jack Honey Shot', desc:"Jack Daniel's Tennessee Honey — honey whiskey is everywhere", wiki:'https://en.wikipedia.org/wiki/Jack_Daniel%27s' },
    beer:{ drink:"Steinlager", desc:"Kiwi green-bottle lager, a world-beater", wiki:"https://en.wikipedia.org/wiki/Steinlager" } },
  { g:'J', flag:'🇦🇷', name:'Argentina', abbr:'ARG', conf:'CONMEBOL',
    auth:{ drink:'Fernet-Branca & Coke', desc:"Bitter herbal liqueur with Coke — Argentina's national cocktail", wiki:'https://en.wikipedia.org/wiki/Fernet' },
    usa:{ drink:'Fernet-Branca Shot', desc:"Actually at most craft bars now — or sub Jager if you can't find it", wiki:'https://en.wikipedia.org/wiki/Fernet-Branca' },
    beer:{ drink:"Quilmes", desc:"Argentina's national lager — sky-blue and white", wiki:"https://en.wikipedia.org/wiki/Cerveza_Quilmes" } },
  { g:'J', flag:'🇦🇹', name:'Austria', abbr:'AUT', conf:'UEFA',
    auth:{ drink:'Stroh Rum', desc:'80% Austrian rum — not for the faint-hearted', wiki:'https://en.wikipedia.org/wiki/Stroh_(rum)' },
    usa:{ drink:'Everclear Shot', desc:'Same brutal ABV energy — or sub Bacardi 151 to survive the night', wiki:'https://en.wikipedia.org/wiki/Everclear_(alcohol)' },
    beer:{ drink:"Stiegl", desc:"Salzburg's independent lager since 1492", wiki:"https://en.wikipedia.org/wiki/Stiegl_Brewery" } },
  { g:'J', flag:'🇩🇿', name:'Algeria', abbr:'ALG', conf:'CAF',
    auth:{ drink:'Mahia', desc:'Date or fig brandy from the Maghreb region', wiki:'https://en.wikipedia.org/wiki/Mahia_(drink)' },
    usa:{ drink:'Brandy Shot', desc:'E&J, Paul Masson, or Christian Brothers — fruit brandy is the family', wiki:'https://en.wikipedia.org/wiki/Brandy' },
    beer:{ drink:"Barbican", desc:"Non-alcoholic malt — the dry-country go-to", wiki:"https://en.wikipedia.org/wiki/Barbican_(drink)" } },
  { g:'J', flag:'🇯🇴', name:'Jordan', abbr:'JOR', conf:'AFC',
    auth:{ drink:'Arak', desc:'Levantine anise spirit — first World Cup, big sip', wiki:'https://en.wikipedia.org/wiki/Arak_(drink)' },
    usa:{ drink:'Sambuca', desc:'Anise liqueur family — Sambuca is the easiest American bar find', wiki:'https://en.wikipedia.org/wiki/Sambuca' },
    beer:{ drink:"Petra", desc:"Jordan's home-grown lager", wiki:"https://en.wikipedia.org/wiki/Beer_in_Jordan" } },
  { g:'K', flag:'🇵🇹', name:'Portugal', abbr:'POR', conf:'UEFA',
    auth:{ drink:'Ginjinha', desc:'Sour cherry liqueur — served in chocolate cups', wiki:'https://en.wikipedia.org/wiki/Ginjinha' },
    usa:{ drink:'Cherry Bounce Shot', desc:'Luxardo Maraschino or Cherry Heering — sour cherry liqueur family', wiki:'https://en.wikipedia.org/wiki/Cherry_Heering' },
    beer:{ drink:"Sagres", desc:"Portugal's golden lager — pairs with pastéis", wiki:"https://en.wikipedia.org/wiki/Sagres_(beer)" } },
  { g:'K', flag:'🇨🇴', name:'Colombia', abbr:'COL', conf:'CONMEBOL',
    auth:{ drink:'Aguardiente', desc:'Anise-flavored sugarcane spirit — party starter', wiki:'https://en.wikipedia.org/wiki/Aguardiente' },
    usa:{ drink:'Sambuca + Sugar Shot', desc:'Similar anise-sweet profile — or white rum with a drop of anise bitters', wiki:'https://en.wikipedia.org/wiki/Sambuca' },
    beer:{ drink:"Águila", desc:"Colombia's beachside lager since 1913", wiki:"https://en.wikipedia.org/wiki/Bavaria_Brewery_(Colombia)" } },
  { g:'K', flag:'🇮🇶', name:'Iraq', abbr:'IRQ', conf:'AFC',
    auth:{ drink:'Arak', desc:'Mesopotamian anise spirit — ancient as the rivers', wiki:'https://en.wikipedia.org/wiki/Arak_(drink)' },
    usa:{ drink:'Sambuca', desc:'Anise family — same approach, much easier to find', wiki:'https://en.wikipedia.org/wiki/Sambuca' },
    beer:{ drink:"Barbican", desc:"Non-alcoholic malt — the regional staple", wiki:"https://en.wikipedia.org/wiki/Barbican_(drink)" } },
  { g:'K', flag:'🇵🇾', name:'Paraguay', abbr:'PAR', conf:'CONMEBOL',
    auth:{ drink:'Caña', desc:'Paraguayan sugarcane spirit, raw and sweet', wiki:'https://en.wikipedia.org/wiki/Ca%C3%B1a_(liquor)' },
    usa:{ drink:'White Rum Shot', desc:'Unaged sugarcane spirit — Bacardi Silver or Plantation 3 Star', wiki:'https://en.wikipedia.org/wiki/Rum' },
    beer:{ drink:"Pilsen", desc:"Paraguay's national lager — simply 'Pilsen'", wiki:"https://en.wikipedia.org/wiki/Cerveza_Pilsen_(Paraguay)" } },
  { g:'L', flag:'🏴󠁧󠁢󠁥󠁮󠁧󠁿', name:'England', abbr:'ENG', conf:'UEFA',
    auth:{ drink:'London Dry Gin', desc:"Double it up — it's coming home", wiki:'https://en.wikipedia.org/wiki/London_dry_gin' },
    usa:{ drink:'Gin Shot', desc:'Tanqueray or Beefeater — London Dry is at every bar', wiki:'https://en.wikipedia.org/wiki/Gin' },
    beer:{ drink:"Carling", desc:"England's best-selling lager — pub standard", wiki:"https://en.wikipedia.org/wiki/Carling_Black_Label" } },
  { g:'L', flag:'🇭🇷', name:'Croatia', abbr:'CRO', conf:'UEFA',
    auth:{ drink:'Šljivovica', desc:'Plum brandy — fierce Balkan tradition', wiki:'https://en.wikipedia.org/wiki/Slivovitz' },
    usa:{ drink:'Slivovitz or Brandy', desc:'Eastern European stores carry Slivovitz — otherwise any dark brandy', wiki:'https://en.wikipedia.org/wiki/Slivovitz' },
    beer:{ drink:"Ožujsko", desc:"Croatia's favourite since 1892 — 'Žuja'", wiki:"https://en.wikipedia.org/wiki/O%C5%BEujsko" } },
  { g:'L', flag:'🇰🇿', name:'Kazakhstan', abbr:'KAZ', conf:'UEFA',
    auth:{ drink:'Kumiss', desc:"Fermented mare's milk — an acquired taste", wiki:'https://en.wikipedia.org/wiki/Kumiss' },
    usa:{ drink:'Kefir + Vodka Shot', desc:"Mix a shot of vodka into plain kefir — as close as you're getting", wiki:'https://en.wikipedia.org/wiki/Kefir' },
    beer:{ drink:"Derbes", desc:"Kazakhstan's home-grown lager", wiki:"https://en.wikipedia.org/wiki/Beer_in_Kazakhstan" } },
  { g:'L', flag:'🇭🇹', name:'Haiti', abbr:'HTI', conf:'CONCACAF',
    auth:{ drink:'Clairin', desc:"Raw sugarcane spirit — Haiti's wild native rum", wiki:'https://en.wikipedia.org/wiki/Clairin' },
    usa:{ drink:'Overproof White Rum', desc:'Rum Fire or Smith & Cross — funky, raw, high-proof sugarcane spirit', wiki:'https://en.wikipedia.org/wiki/Overproof_rum' },
    beer:{ drink:"Prestige", desc:"Haiti's award-winning lager, national pride", wiki:"https://en.wikipedia.org/wiki/Prestige_(beer)" } },
]

// Drink modes, in toggle order. Each team carries a Drink for every mode.
export const MODES: Mode[] = ['auth', 'usa', 'beer']

// Per-mode toggle label.
export const MODE_META: Record<Mode, { label: string }> = {
  auth: { label: 'Authentic' },
  usa:  { label: 'American Bar' },
  beer: { label: 'Beer' },
}

// YYYY-MM-DD for a Date, expressed in the browser's local timezone.
// (Date#getFullYear/getMonth/getDate read local-time fields, unlike toISOString which is UTC.)
export function toLocalDateStr(d: Date): string {
  const y = d.getFullYear()
  const m = String(d.getMonth() + 1).padStart(2, '0')
  const day = String(d.getDate()).padStart(2, '0')
  return `${y}-${m}-${day}`
}

// Today's date as YYYY-MM-DD in the browser's local timezone.
// Call this on the client (e.g. inside an effect) so it reflects the viewer's
// timezone rather than the server's at build/SSR time.
export function localToday(): string {
  return toLocalDateStr(new Date())
}

export const teamByAbbr = (abbr: string) => TEAMS.find(t => t.abbr === abbr)
